###############################################################################
#
# © Copyright IBM Corp. 2020, 2023, 2024
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: development
  namespace: eks-event-streams
spec:
  version: latest
  license:
    # By installing this product you accept the license terms at https://ibm.biz/ea-license
    accept: true
    license: "L-AUKS-FKVXVL"
    use: "EventAutomationDevelopment"
  adminApi:
    endpoints:
      - name: ingress
        type: ingress
        host: adminapi.<external_ip_address>.nip.io
        class: nginx
        containerPort: 8001
  adminUI:
    authentication:
      - type: scram-sha-512
    endpoints:
      - name: ingress
        type: ingress
        host: adminui.<external_ip_address>.nip.io
        class: nginx
        containerPort: 3000
  apicurioRegistry:
    endpoints:
      - name: ingress
        type: ingress
        host: apicurio.<external_ip_address>.nip.io
        class: nginx
        containerPort: 8002
  restProducer:
    endpoints:
      - name: ingress
        type: ingress
        host: restproducer.<external_ip_address>.nip.io
        class: nginx
        containerPort: 8003
  strimziOverrides:
    kafka:
      authorization:
        type: simple
      config:
        inter.broker.protocol.version: "3.9"
        log.cleaner.threads: 6
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 3
        offsets.topic.replication.factor: 3
        default.replication.factor: 3
        min.insync.replicas: 2
        auto.create.topics.enable: 'false'
      listeners:
        - name: external
          port: 9094
          type: ingress
          tls: true
          authentication:
            type: scram-sha-512
          configuration:
            bootstrap:
              host: kafka-bootstrap.eventstreams.<external_ip_address>.nip.io
            brokers:
              - broker: 0
                host: kafka-0.eventstreams.<external_ip_address>.nip.io
              - broker: 1
                host: kafka-1.eventstreams.<external_ip_address>.nip.io
              - broker: 2
                host: kafka-2.eventstreams.<external_ip_address>.nip.io
            class: nginx
        - name: tls
          port: 9093
          type: internal
          tls: true
          authentication:
            type: tls
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: development-metrics-config
    zookeeper:
      replicas: 3
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: development-metrics-config
      storage:
        type: ephemeral
    nodePools:
      - name: kafka
        replicas: 3
        storage:
          type: ephemeral
        roles:
          - broker
